version: '3'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - C:/student_data:/data 

  frontend:
    image: nginx:alpine
    volumes:
      - ./:/usr/share/nginx/html:ro  # fixed path
    ports:
      - "8080:80"